2024-05-07 14:16:37 | INFO | controller | args: Namespace(host='0.0.0.0', port=10000, dispatch_method='shortest_queue')
2024-05-07 14:16:37 | INFO | controller | Init controller
2024-05-07 14:16:37 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1939703[0m]
2024-05-07 14:16:37 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-05-07 14:16:37 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-05-07 14:16:37 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:10000[0m (Press CTRL+C to quit)
2024-05-07 14:16:48 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-05-07 14:16:49 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-05-07 14:16:49 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-05-07 14:16:49 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m1939703[0m]
2024-05-07 14:16:49 | ERROR | stderr | Exception ignored in: <module 'threading' from '/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/threading.py'>
2024-05-07 14:16:49 | ERROR | stderr | Traceback (most recent call last):
2024-05-07 14:16:49 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/threading.py", line 1567, in _shutdown
2024-05-07 14:16:49 | ERROR | stderr |     lock.acquire()
2024-05-07 14:16:49 | ERROR | stderr | KeyboardInterrupt:
2024-05-07 14:17:03 | INFO | controller | args: Namespace(host='127.0.0.1', port=50000, dispatch_method='shortest_queue')
2024-05-07 14:17:03 | INFO | controller | Init controller
2024-05-07 14:17:03 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1939864[0m]
2024-05-07 14:17:03 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-05-07 14:17:03 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-05-07 14:17:03 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:50000[0m (Press CTRL+C to quit)
2024-05-07 14:17:24 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60252 - "[1mGET /?vscodeBrowserReqId=1715062643891 HTTP/1.1[0m" [31m404 Not Found[0m
2024-05-07 14:17:40 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-05-07 14:17:40 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-05-07 14:17:40 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-05-07 14:17:40 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m1939864[0m]
2024-05-07 14:17:40 | ERROR | stderr | Exception ignored in: <module 'threading' from '/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/threading.py'>
2024-05-07 14:17:40 | ERROR | stderr | Traceback (most recent call last):
2024-05-07 14:17:40 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/threading.py", line 1567, in _shutdown
2024-05-07 14:17:40 | ERROR | stderr |     lock.acquire()
2024-05-07 14:17:40 | ERROR | stderr | KeyboardInterrupt:
